run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gofmt:
    simplify: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
