//go:build ignore

package main

import (
	"os"
	"strings"
	"text/template"
)

var types = []string{
	"DocumentResponse",
	"GetResponse",
	"MGetResponse",
	"BulkResponse",
	"SearchResponse",
	"CountResponse",
	"DeleteByQueryResponse",
	"UpdateByQueryResponse",
	"ScrollResponse",
	"SearchAfterResponse",
	"AggregationResponse",
	"IndexInfo",
	"ClusterHealthResponse",
	"ClusterStateResponse",
	"ClusterStatsResponse",
	"NodesInfoResponse",
	"NodesStatsResponse",
	"TasksResponse",
	"ClusterSettingsResponse",
	"AllocationExplainResponse",
}

const tpl = `// Code generated by gen_json_methods.go; DO NOT EDIT.

package builder

import "encoding/json"

// JSONSerializer JSON 序列化接口
type JSONSerializer interface {
	JSON() string
	PrettyJSON() string
	String() string
}

// ToJSON 返回任意结构体的紧凑 JSON 字符串
func ToJSON(v any) string {
	data, _ := json.Marshal(v)
	return string(data)
}

// ToPrettyJSON 返回任意结构体的格式化 JSON 字符串
func ToPrettyJSON(v any) string {
	data, _ := json.MarshalIndent(v, "", "  ")
	return string(data)
}
{{range .}}
func (r *{{.}}) JSON() string       { return ToJSON(r) }
func (r *{{.}}) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *{{.}}) String() string     { return r.PrettyJSON() }
{{end}}`

func main() {
	t := template.Must(template.New("methods").Parse(tpl))

	f, err := os.Create("response_ext_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	// 移除多余空行
	var sb strings.Builder
	if err := t.Execute(&sb, types); err != nil {
		panic(err)
	}

	// 写入文件
	f.WriteString(sb.String())
}
