// Code generated by gen_json_methods.go; DO NOT EDIT.

package builder

import "encoding/json"

// JSONSerializer JSON 序列化接口
type JSONSerializer interface {
	JSON() string
	PrettyJSON() string
	String() string
}

// ToJSON 返回任意结构体的紧凑 JSON 字符串
func ToJSON(v any) string {
	data, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	return string(data)
}

// ToPrettyJSON 返回任意结构体的格式化 JSON 字符串
func ToPrettyJSON(v any) string {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return ""
	}
	return string(data)
}

func (r *DocumentResponse) JSON() string       { return ToJSON(r) }
func (r *DocumentResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *DocumentResponse) String() string     { return r.PrettyJSON() }

func (r *GetResponse) JSON() string       { return ToJSON(r) }
func (r *GetResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *GetResponse) String() string     { return r.PrettyJSON() }

func (r *MGetResponse) JSON() string       { return ToJSON(r) }
func (r *MGetResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *MGetResponse) String() string     { return r.PrettyJSON() }

func (r *BulkResponse) JSON() string       { return ToJSON(r) }
func (r *BulkResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *BulkResponse) String() string     { return r.PrettyJSON() }

func (r *SearchResponse) JSON() string       { return ToJSON(r) }
func (r *SearchResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *SearchResponse) String() string     { return r.PrettyJSON() }

func (r *CountResponse) JSON() string       { return ToJSON(r) }
func (r *CountResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *CountResponse) String() string     { return r.PrettyJSON() }

func (r *DeleteByQueryResponse) JSON() string       { return ToJSON(r) }
func (r *DeleteByQueryResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *DeleteByQueryResponse) String() string     { return r.PrettyJSON() }

func (r *UpdateByQueryResponse) JSON() string       { return ToJSON(r) }
func (r *UpdateByQueryResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *UpdateByQueryResponse) String() string     { return r.PrettyJSON() }

func (r *ScrollResponse) JSON() string       { return ToJSON(r) }
func (r *ScrollResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *ScrollResponse) String() string     { return r.PrettyJSON() }

func (r *SearchAfterResponse) JSON() string       { return ToJSON(r) }
func (r *SearchAfterResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *SearchAfterResponse) String() string     { return r.PrettyJSON() }

func (r *AggregationResponse) JSON() string       { return ToJSON(r) }
func (r *AggregationResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *AggregationResponse) String() string     { return r.PrettyJSON() }

func (r *IndexInfo) JSON() string       { return ToJSON(r) }
func (r *IndexInfo) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *IndexInfo) String() string     { return r.PrettyJSON() }

func (r *ClusterHealthResponse) JSON() string       { return ToJSON(r) }
func (r *ClusterHealthResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *ClusterHealthResponse) String() string     { return r.PrettyJSON() }

func (r *ClusterStateResponse) JSON() string       { return ToJSON(r) }
func (r *ClusterStateResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *ClusterStateResponse) String() string     { return r.PrettyJSON() }

func (r *ClusterStatsResponse) JSON() string       { return ToJSON(r) }
func (r *ClusterStatsResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *ClusterStatsResponse) String() string     { return r.PrettyJSON() }

func (r *NodesInfoResponse) JSON() string       { return ToJSON(r) }
func (r *NodesInfoResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *NodesInfoResponse) String() string     { return r.PrettyJSON() }

func (r *NodesStatsResponse) JSON() string       { return ToJSON(r) }
func (r *NodesStatsResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *NodesStatsResponse) String() string     { return r.PrettyJSON() }

func (r *TasksResponse) JSON() string       { return ToJSON(r) }
func (r *TasksResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *TasksResponse) String() string     { return r.PrettyJSON() }

func (r *ClusterSettingsResponse) JSON() string       { return ToJSON(r) }
func (r *ClusterSettingsResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *ClusterSettingsResponse) String() string     { return r.PrettyJSON() }

func (r *AllocationExplainResponse) JSON() string       { return ToJSON(r) }
func (r *AllocationExplainResponse) PrettyJSON() string { return ToPrettyJSON(r) }
func (r *AllocationExplainResponse) String() string     { return r.PrettyJSON() }
